version: '3.8'

services:
  kong:
    image: mcntech/arcturus-kong
    environment:
      - KONG_DATABASE=off
      - KONG_LOG_LEVEL=debug
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
    restart: on-failure

  redis:
    image: redis

  test-echo-server:
    image: mcntech/test-srv-echo
    ports:
      - '9430:8080'

  arcturus:
    image: mcntech/arcturus
    environment:
      - CONTRACT=0x00000005Ff125830A53F5e6F53A37854C250f315
      - RPC=""
    ports:
      - '8188:8188'
    restart: on-failure

volumes:
  shared-volume:
    

networks:
  default:
    name: arcturus-network
